{{- $name := include "coupon-api.fullname" . -}}
{{- $sqlsrv := include "mongo-name" . -}}
{{- $webshoppingapigw := include "url-of" (list .Values.app.ingress.entries.webshoppingapigw .) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "coupon-api.name" . }}
    chart: {{ template "coupon-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  coupon__ConnectionString: mongodb://{{ $sqlsrv }}:27017
  coupon__AzureStorageEnabled: "{{ .Values.inf.misc.useAzureStorage }}"
  all__EventBusConnection: {{ .Values.inf.eventbus.constr }}
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"
  urls__IdentityUrl: http://{{ .Values.app.svc.identity }}